# Generated by Django 3.1.6 on 2021-03-03 05:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('OTP', models.IntegerField()),
                ('Role', models.CharField(max_length=50)),
                ('is_verifed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_updated', models.DateTimeField(auto_now_add=True)),
                ('is_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('Contact', models.BigIntegerField(default='123')),
                ('DOB', models.DateField(default='2020-12-01')),
                ('Gender', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('Experience', models.CharField(max_length=50)),
                ('Designation', models.CharField(max_length=50)),
                ('Specilazation', models.CharField(max_length=50)),
                ('Working_hrs_start', models.TimeField(default=datetime.time(16, 0))),
                ('Working_hrs_end', models.TimeField(default=datetime.time(18, 0))),
                ('profile_pic', models.ImageField(default='/img/default-user.jpg', upload_to='img/')),
                ('ver_doc', models.FileField(default='/ver_doc/default.pdf', upload_to='ver_doc/')),
                ('m_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.master_table')),
            ],
        ),
    ]
