# Generated by Django 3.1.6 on 2021-03-03 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('Contact', models.BigIntegerField(default='123')),
                ('DOB', models.DateField(default='2020-12-01')),
                ('Gender', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(default='/img/default-user.jpg', upload_to='img/')),
                ('m_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.master_table')),
            ],
        ),
    ]
