# Generated by Django 3.1.6 on 2021-03-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='Intro',
            field=models.CharField(default='Your Intro', max_length=300),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Experience',
            field=models.CharField(max_length=200),
        ),
    ]
