# Generated by Django 3.1.6 on 2021-03-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210305_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Gender',
            field=models.CharField(default='SELECT', max_length=50),
        ),
    ]
