# Generated by Django 3.1.6 on 2021-03-05 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210305_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='Working_hrs_end',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Working_hrs_start',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
