# Generated by Django 3.1.6 on 2021-03-08 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210308_1004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Patient',
        ),
    ]
