# Generated by Django 3.1.6 on 2021-03-10 06:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_delete_appoinment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoinment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking_date', models.DateField(default='2020-12-01')),
                ('Booking_time', models.TimeField(default=datetime.time(0, 0))),
                ('Visits', models.CharField(max_length=50)),
                ('Currentstatus', models.CharField(default='Pending', max_length=50)),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
    ]
