# Generated by Django 3.1.6 on 2021-03-10 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_appoinment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appoinment',
        ),
    ]
