# Generated by Django 3.1.6 on 2021-04-13 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210316_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Currentstatus', models.CharField(default='Open', max_length=50)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('Remarks', models.CharField(max_length=200)),
                ('medical_history', models.CharField(max_length=200)),
                ('allergic', models.CharField(max_length=200)),
                ('appoint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.appoinment')),
            ],
        ),
    ]
